using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("DbNetSuite")]
[assembly: AssemblyDescription("ASP.NET Ajax Development Components")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("DbNetLink Limited")]
[assembly: AssemblyProduct("DbNetSuite")]
[assembly: AssemblyCopyright("Copyright © 2021")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("0042e582-1692-41f5-bb20-24a498232d31")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]
[assembly: AssemblyVersion("4.4.*")]
[assembly: AssemblyFileVersion("4.4.0.0")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.csg-4f4f550b4d3f0.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.next.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.AddFolder.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Asc.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Collapse.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.copy.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Desc.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.DialogCloseButton.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.DialogCloseButtonMouseDown.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.DialogCloseButtonMouseOver.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.DialogResize.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.DialogTitlebar.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.download.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Error.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Error32.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Expand.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.FolderClosed.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.FolderOpen.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Help.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Info.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Info32.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.LeftArrow.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.NewFolder.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.nofile.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.ok.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Question.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Question32.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.RightArrow.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Upload.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.wait.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Warning.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Warning32.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.window.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.nicEditorIcons.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.required.png", "image/png")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.printer.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.next.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.prev.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.first.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.last.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.update.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.insert.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.find.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.delete.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.save.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.calendar.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.image_add.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.image_delete.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.edit.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.lookup.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.apply.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.refresh.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.undo.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.folder_find.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.parentfolder.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.upload.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.spellcheck.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.new_search.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.UserProfile.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Browse.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Cancel.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.MailMerge.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Up.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Down.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Left.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Right.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.ColumnPicker.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.GreenDown.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Sort.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Options.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Chart.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Serialize.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.zoom.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.view.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.view.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.ajax-loader.gif", "image/gif")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.ui-icons_454545_256x240.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.ui-icons_222222_256x240.png", "image/png")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.chm.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.config.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.css.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.csv.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.default.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.doc.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.folder.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.gif.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.htm.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.jpeg.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.jpg.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.mdb.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.pdf.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.png.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.ppt.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.rtf.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.tif.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.txt.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.unknown.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.vsd.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.wav.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.xls.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.xml.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.zip.gif", "image/gif")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.docx.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.docm.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.dotx.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.dotm.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.xlsx.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.xlsm.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.xltx.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.xltm.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.xlsb.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.xlam.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.pptx.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.pptm.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.potx.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.potm.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.ppam.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.ppsx.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.ppsm.gif", "image/gif")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.vdx.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.vsd.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.vss.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.vst.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.vsx.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Ext.vtx.gif", "image/gif")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Tree.tree-last-node-close.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Tree.tree-last-node-open.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Tree.tree-last-node.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Tree.tree-node-close.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Tree.tree-node-open.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Tree.tree-node.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.Tree.tree-vertical-line.gif", "image/gif")]


[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_flat_0_aaaaaa_40x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_flat_75_ffffff_40x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_flat_75_dcdcdc_40x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_glass_55_fbf9ee_1x400.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_glass_75_dadada_1x400.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_glass_75_e6e6e6_1x400.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_glass_95_fef1ec_1x400.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_highlight-soft_75_cccccc_1x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-icons_2e83ff_256x240.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-icons_454545_256x240.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-icons_888888_256x240.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-icons_cd0a0a_256x240.png", "image/png")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-icons_222222_256x240.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_glass_65_ffffff_1x400.png", "image/png")]


[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-icons_cd0a0a_256x240.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-icons_cd0a0a_256x240.png", "image/png")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_diagonals-thick_18_b81900_40x40.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_diagonals-thick_20_666666_40x40.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_flat_10_000000_40x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_glass_100_f6f6f6_1x400.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_glass_100_fdf5ce_1x400.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_gloss-wave_35_f6a828_500x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_highlight-soft_100_eeeeee_1x100.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-bg_highlight-soft_75_ffe45c_1x100.png", "image/png")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-icons_228ef1_256x240.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-icons_ef8c08_256x240.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-icons_ffd27a_256x240.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.jQueryUI.ui-icons_ffffff_256x240.png", "image/png")]


[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Html.Empty.htm", "text/html")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Html.UploadPage.htm", "text/html")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.HTA.mailmerge.hta", "application/hta")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Xml.mime-types.xml", "text/xml")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.jquery-1.8.1.min.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.jquery-ui-1.9.2.custom.min.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.jquery-ui-1.11.2.custom.min.js", "text/javascript")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.jquery.browser.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.jquery.hotkeys.js", "text/javascript")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.json2.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.class.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DbNetLink.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DbNetSuite.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.MessageBox.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.GridEditControl.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DbNetGrid.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DbNetEdit.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DbNetFile.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DbNetSpell.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DbNetCombo.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DbNetList.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.jquery.tooltip.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.jquery.maxlength.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.jquery.fixedheader.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.to-title-case.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.Dialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.SearchDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.SearchPanel.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.LookupDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.SimpleSearchDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.AdvancedSearchDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.ErrorDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.EditDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.UploadDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.AjaxUploadDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.SuggestLookup.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.TextEditor.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.HtmlEditor.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.FileSearchDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.FileSearchResultsDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.FilePreviewDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.NewFolderDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.PdfSettingsDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DbNetSpellDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.nicEdit.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.UserProfileDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.BrowseDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.office.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.ColumnPickerDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.ColumnSortDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.jquery.bgiframe.min.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.ConfigDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.ChartConfigDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.ChartDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.jquery.placeholder.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.AuditDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.ViewDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DataUploadDialog.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.jquery-ui-timepicker-addon.js", "text/javascript")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DbNetGrid.Compat.Properties.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DbNetGrid.Compat.Code.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DbNetEdit.Compat.Properties.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.DbNetEdit.Compat.Code.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.console.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.CssToInlineStyle.js", "text/javascript")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Scripts.clipboard.min.js", "text/javascript")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.DbNetSuite.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.DbNetGrid.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.DbNetEdit.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.DbNetFile.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.DbNetCombo.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.DbNetList.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.jquery-ui-1.9.2.custom.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.jquery-ui-1.11.2.custom.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.SuggestLookup.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.jquery.placeholder.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.ViewDialog.css", "text/css")]

[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.Themes.light.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.Themes.dark.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.Themes.bootstrap.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.CSS.Themes.bootstrap.mod.css", "text/css")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.light.Asc.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.light.Desc.gif", "image/gif")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.bootstrap.collapse.png", "image/png")]
[assembly: System.Web.UI.WebResource("DbNetLink.Resources.Images.bootstrap.expand.png", "image/png")]