//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbNetLink.DbNetSuiteVS.Resources.Localisation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class _default {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _default() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DbNetLink.Resources.Localisation.default", typeof(_default).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        internal static string Advanced {
            get {
                return ResourceManager.GetString("Advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After.
        /// </summary>
        internal static string After {
            get {
                return ResourceManager.GetString("After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        internal static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required for.
        /// </summary>
        internal static string AValueIsRequiredFor {
            get {
                return ResourceManager.GetString("AValueIsRequiredFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before.
        /// </summary>
        internal static string Before {
            get {
                return ResourceManager.GetString("Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between.
        /// </summary>
        internal static string Between {
            get {
                return ResourceManager.GetString("Between", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy To Clipboard.
        /// </summary>
        internal static string CopyToClipboard {
            get {
                return ResourceManager.GetString("CopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value entered into &lt;b&gt;{0}&lt;/b&gt; is not valid for data type.
        /// </summary>
        internal static string DataMismatch {
            get {
                return ResourceManager.GetString("DataMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to the database.
        /// </summary>
        internal static string DbConnectionError {
            get {
                return ResourceManager.GetString("DbConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting of records is not enabled for for this control.
        /// </summary>
        internal static string DeleteDisabled {
            get {
                return ResourceManager.GetString("DeleteDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not Contain.
        /// </summary>
        internal static string DoesNotContain {
            get {
                return ResourceManager.GetString("DoesNotContain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not end with.
        /// </summary>
        internal static string DoesNotEndWith {
            get {
                return ResourceManager.GetString("DoesNotEndWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not start with.
        /// </summary>
        internal static string DoesNotStartWith {
            get {
                return ResourceManager.GetString("DoesNotStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends with.
        /// </summary>
        internal static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equal to.
        /// </summary>
        internal static string EqualTo {
            get {
                return ResourceManager.GetString("EqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in column property.
        /// </summary>
        internal static string ErrorInColumnProperty {
            get {
                return ResourceManager.GetString("ErrorInColumnProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in Column definitions.
        /// </summary>
        internal static string ErrorInColumns {
            get {
                return ResourceManager.GetString("ErrorInColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in &lt;b&gt;FixedFilter&lt;/b&gt; property.
        /// </summary>
        internal static string ErrorInFixedFilter {
            get {
                return ResourceManager.GetString("ErrorInFixedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in &lt;b&gt;FixedOrderBy&lt;/b&gt; property.
        /// </summary>
        internal static string ErrorInFixedOrderBy {
            get {
                return ResourceManager.GetString("ErrorInFixedOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in &lt;b&gt;FromPart&lt;/b&gt; property.
        /// </summary>
        internal static string ErrorInFromPart {
            get {
                return ResourceManager.GetString("ErrorInFromPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in &lt;b&gt;InitialOrderBy&lt;/b&gt; property.
        /// </summary>
        internal static string ErrorInInitialOrderBy {
            get {
                return ResourceManager.GetString("ErrorInInitialOrderBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in column &lt;b&gt;Lookup&lt;/b&gt; property.
        /// </summary>
        internal static string ErrorInLookup {
            get {
                return ResourceManager.GetString("ErrorInLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export current page only.
        /// </summary>
        internal static string ExportCurrentPageOnly {
            get {
                return ResourceManager.GetString("ExportCurrentPageOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed custom validation.
        /// </summary>
        internal static string FailedCustomValidation {
            get {
                return ResourceManager.GetString("FailedCustomValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string False {
            get {
                return ResourceManager.GetString("False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file exceeds the maximum permitted file size.  Please upload a file smaller than {0}Kb.
        /// </summary>
        internal static string FileExceedsMaxSize {
            get {
                return ResourceManager.GetString("FileExceedsMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Upload.
        /// </summary>
        internal static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First page.
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greater than.
        /// </summary>
        internal static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML Editor.
        /// </summary>
        internal static string HtmlEditor {
            get {
                return ResourceManager.GetString("HtmlEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting of records is not enabled for for this control.
        /// </summary>
        internal static string InsertDisabled {
            get {
                return ResourceManager.GetString("InsertDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is not null.
        /// </summary>
        internal static string IsNotNull {
            get {
                return ResourceManager.GetString("IsNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is null.
        /// </summary>
        internal static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last page.
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Less than.
        /// </summary>
        internal static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match all of the criteria.
        /// </summary>
        internal static string MatchAllCriteria {
            get {
                return ResourceManager.GetString("MatchAllCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match at least one of the criteria.
        /// </summary>
        internal static string MatchAtLeastOneCriteria {
            get {
                return ResourceManager.GetString("MatchAtLeastOneCriteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;b&gt;ConnectionString&lt;/b&gt; property has not been set for this control.
        /// </summary>
        internal static string NoConnectionString {
            get {
                return ResourceManager.GetString("NoConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreign Key fields must be specified for child controls.
        /// </summary>
        internal static string NoForeignKeys {
            get {
                return ResourceManager.GetString("NoForeignKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;FromPart&lt;/b&gt; property has not been defined.
        /// </summary>
        internal static string NoFromPart {
            get {
                return ResourceManager.GetString("NoFromPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not between.
        /// </summary>
        internal static string NotBetween {
            get {
                return ResourceManager.GetString("NotBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not equal to.
        /// </summary>
        internal static string NotEqualTo {
            get {
                return ResourceManager.GetString("NotEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not greater than.
        /// </summary>
        internal static string NotGreaterThan {
            get {
                return ResourceManager.GetString("NotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not in.
        /// </summary>
        internal static string NotIn {
            get {
                return ResourceManager.GetString("NotIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not less than.
        /// </summary>
        internal static string NotLessThan {
            get {
                return ResourceManager.GetString("NotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open In New Window.
        /// </summary>
        internal static string OpenInNewWindow {
            get {
                return ResourceManager.GetString("OpenInNewWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        internal static string PreviousPage {
            get {
                return ResourceManager.GetString("PreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted.
        /// </summary>
        internal static string RecordDeleted {
            get {
                return ResourceManager.GetString("RecordDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record inserted.
        /// </summary>
        internal static string RecordInserted {
            get {
                return ResourceManager.GetString("RecordInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records deleted.
        /// </summary>
        internal static string RecordsDeleted {
            get {
                return ResourceManager.GetString("RecordsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated.
        /// </summary>
        internal static string RecordUpdated {
            get {
                return ResourceManager.GetString("RecordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename File:.
        /// </summary>
        internal static string RenameFile {
            get {
                return ResourceManager.GetString("RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Value.
        /// </summary>
        internal static string SelectValue {
            get {
                return ResourceManager.GetString("SelectValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple.
        /// </summary>
        internal static string Simple {
            get {
                return ResourceManager.GetString("Simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts with.
        /// </summary>
        internal static string StartsWith {
            get {
                return ResourceManager.GetString("StartsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Editor.
        /// </summary>
        internal static string TextEditor {
            get {
                return ResourceManager.GetString("TextEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string True {
            get {
                return ResourceManager.GetString("True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find parent control with ID:.
        /// </summary>
        internal static string UnableToFindParentControl {
            get {
                return ResourceManager.GetString("UnableToFindParentControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating of records is not enabled for for this control.
        /// </summary>
        internal static string UpdatesDisabled {
            get {
                return ResourceManager.GetString("UpdatesDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload .
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload complete.
        /// </summary>
        internal static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
