name: Debug Build DbNetSuite

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: List files in the workspace
      run: dir /s
      shell: cmd

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore and Build the solution
      run: msbuild.exe DbNetSuite.sln /t:Restore,Build /p:Configuration=Release
