name: Build DbNetSuite

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    # Langkah 'nuget restore' yang lama sudah dihapus

    - name: Restore and Build the solution
      run: msbuild.exe DbNetSuite.sln /t:Restore,Build /p:Configuration=Release

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DbNetSuite-DLL
        path: DbNetSuite/bin/Release/DbNetSuite.dll
