name: Build DbNetSuite

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore and Build the solution
      run: msbuild.exe "DbNetSuite 4.4.sln" /t:Restore,Build /p:Configuration=Release /p:OutputPath=bin\Release\

    - name: Upload DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DbNetSuite-DLL
        path: bin/Release/DbNetLink.DbNetSuite.dll
